### PR TITLE
Add create_dev.yml and configure_dev.yml.

### PR DESCRIPTION
**Pull request by hackartisan**
- create_dev exists to call configure_dev.
- Mostly these are a bunch of notes for now.
- Feel free to reject this PR if it's useless.

### CODE REVIEW

**Comment by mark-dce** [comment]
I'd like to have a conversation about how many canonical playbooks we maintain in this repo.  I'm concerned that as the number of playbooks grow, it's difficult and time consuming to ensure they all remain valid as we make updates to existing roles.  I like the pattern of putting playbooks in separate repos that point to ansibl-hydra as a submodule at a specific commit because it insulates existing playbooks from unintended consequences of commits to the master branch.  

There might be better ways to address my concern that I'm not thinking of though.

**Comment by acozine** [comment]
What about a pattern where we have sample playbooks for a variety of use cases, including vagrant builds, ec2 builds, etc.? The samples in this repo could use the default variables, while the fully-customized playbook files could live in the code repos they're connected to.

**Comment by hackartisan** [comment]
I don't have strong feelings one way or another. I offered to either submit these playbooks or write up my notes on the wiki  -- I do think the playbooks are easier to maintain than the wiki, and easier to digest than some attempt at narrativizing the process.

I won't likely be publishing my local playbooks because they are housed in the private repo with our sensitive data. We may consider breaking our setup apart further but it seems like a lot of extra complication that is not in the short-term plan.

What if we comment some playbooks as examples, not guaranteed to be in line with the current set of scripts, and others as maintained / current?

**Comment by mark-dce** [comment]
I'd be up for having some way to flag the playbooks that are guaranteed to be kept up-to date vs. the ones that are there as (possibly) non-maintained examples.  Would it work to put unmaintained playbooks in a subdirectory and maintained ones at the top-level of the repo?

**Comment by hackartisan** [comment]
sounds like a good idea; something like examples/ with a little readme saying the contents of this dir aren't guaranteed to be maintained.

**Comment by mark-dce** [comment]
I added a new Issue to capture the idea of separating guaranteed playbooks (we keep up-to-date and test with every change) vs. reference playbooks that might not always be 100% up to date.  Feel free to add comments or ideas to #108.

**Comment by mark-dce** [comment]
@hackmastera I've merged the related pull request. You can delete the `dev-playbook` branch if you don't need it anymore.

**Pull request merged**
